# Generated by Django 5.1.4 on 2026-02-09 08:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_remove_cartitem_size_variant_and_more'),
        ('products', '0015_productreview_dislikes_productreview_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size_variant',
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('user', 'product')},
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='size_variant',
        ),
        migrations.DeleteModel(
            name='SizeVariant',
        ),
    ]
