# Generated by Django 5.1.4 on 2026-02-09 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_orderitem_product_price_alter_orderitem_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='size_variant',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='size_variant',
        ),
    ]
